name: Run Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
#
#    - name: Checkout exercise feedback
#      uses: actions/checkout@v3
#      with:
#        repository: jvalue/made-exercise-feedback
#        path: grading

#    - name: Set up Node
#      uses: actions/setup-node@v3
#      with:
#        node-version: 'lts/*'

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install dependencies
      run: |
        cd main
        pip install --upgrade pip
        pip install -r project/requirements.txt

    # Run tests
    - name: Run Test
      run: |
        cd main
        chmod +x project/tests.sh
        project/tests.sh